<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LakeWright.Multitenancy\LakeWright.Multitenancy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LakeWright.DatabaseMaintenance" />
    <InternalsVisibleTo Include="LakeWright.TenantIsolation.Tests" />
  </ItemGroup>
</Project>
